version: '2'

services:
  jupyterlab:
    image: 'jupyterlab:latest'
    container_name: jupyterlab
    hostname: 'localhost'
    ports:
      - '8888:8888'
    volumes:
      - './jupyter:/home/jupyter/work'
    command: jupyter lab --ip=0.0.0.0
 
